#give me docker compose for mongodb

version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  api:
    build: .
    container_name: api
    restart: always
    ports:
      - 8080:8080

volumes:
  mongodb_data:
    driver: local
